name: Fifth Workflow
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Step1 from job1
        run: python script1.py
  job2:
    runs-on: ubuntu-latest
    needs:
      job1
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Step2 from job2
        run: python script2.py
  job3:
    runs-on: ubuntu-latest
    needs:
      job2
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Step3 from job3
        run: python script3.py
  job4:
    runs-on: ubuntu-latest
    needs:
      job2
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Step4 from job4
        run: python script4.py
  job5:
    runs-on: ubuntu-latest
    needs:
      [job3,job4]
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Step5 from job5
        run: python script5.py  
