name: Second-Workflow-ENV-Variables
on:
  workflow_dispatch:
env:
  workflow_message: "I am defined on workflow level"

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      job1_message: "I am defined in job1 level"
    steps:
      - name: Executing step level
        env:
          step_message: "I am defined in message level"
        run: |
          echo "Workflow-message:$workflow_message"
          echo "Job1-message:$job1_message"
          echo "Step-message:$step_message"

