name: Matrix test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13.15","3.14.7"]
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/checkout@v5
        with:
          python: ${{matrix.python-version}}
      - name: Show Version
        run: python --version
      - name: Run code
        run: python script1.py
        env:
          APP_ENV: staging
