name: Run on different versions

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12","3.13"]
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run code
        env:
          APP_ENV: staging
        run: python Python-Scripts/script1.py
