name: ENV VARIABLES
on: 
  workflow_dispatch:
env:
  WORKFLOW_VAR: "I am workflow-scoped var"
jobs:
  job1:
    env:
      JOB_VAR: "This is job-scoped var"
    name: "Job-1"
    runs-on: ubuntu-latest
    steps:
      - name: "Job1"
        env:
          STEP_VAR: "This is a job-scoped var"
        run: echo "Hello World"
  job2:
    runs-on: ubuntu-latest
    name: "This is 2nd Job"
    steps:
      - name: "Job2"
        run: |
          echo "Hello World'
          echo "$WORKFLOW_VAR"
          echo "JOB_VAR is not defined in this scope" # not defined here
          echo "STEP_VAR is not defined in this scope" # not defined here
        
      
